### ISSUE TITLE
More sources

### ISSUE THREAD

**Issue by felixd** [whitefight18/hashcat_benchmark#2]
Hello, if You guys are looking for more results check that:
https://gitlab.com/vay3t/hashcatbenchmark

My benchmark results for NVidia 980Ti
[hashcat-GeForce_980Ti-benchmark-ALL.txt](https://github.com/whitefight18/hashcat_benchmark/files/10420211/hashcat-GeForce_980Ti-benchmark-ALL.txt)
[hashcat-GeForce_980Ti-benchmark-SHORT.txt](https://github.com/whitefight18/hashcat_benchmark/files/10420213/hashcat-GeForce_980Ti-benchmark-SHORT.txt)

If you want to talk I am on Discord: https://bit.ly/flameit-discord

Regards, Paweł.

**Comment by whitefight18** [comment]
Hey Paweł, thanks for the resources and the link.

Also, if you want to merge the benchmark files that you provided, you can raise a pull request, I'll merge it to my repo :D

**Comment by whitefight18** [comment]
Hey Paweł, thanks for the resources and the link.

Also, if you want to merge the benchmark files that you provided, you can raise a pull request, I'll merge it to my repo :D
